class RoadmapData {
  static final List<Map<String, dynamic>> phases = [
    {
      'phase': 1,
      'title': 'REBUILD JAVA BASICS',
      'color': 0xFF00FF88,
      'icon': '☕',
      'topics': [
        {
          'name': 'Java Fundamentals',
          'subtopics': [
            'Variables & Data Types',
            'Operators',
            'Control Flow (if/else, switch)',
            'Loops (for, while, do-while)',
            'Arrays',
            'Strings & String Methods',
            'Type Casting',
            'Input/Output',
            'Methods & Functions',
            'Packages & Access Modifiers',
          ],
        },
        {
          'name': 'OOPS',
          'subtopics': [
            'Classes & Objects',
            'Constructors',
            'Inheritance',
            'Polymorphism',
            'Abstraction',
            'Encapsulation',
            'Interfaces',
            'Abstract Classes',
            'this & super keywords',
            'Method Overloading & Overriding',
          ],
        },
        {
          'name': 'Collections',
          'subtopics': [
            'ArrayList',
            'LinkedList',
            'HashMap',
            'HashSet',
            'TreeMap',
            'Queue & PriorityQueue',
            'Stack',
            'Iterators',
            'Comparable & Comparator',
            'Collections Utility Class',
          ],
        },
        {
          'name': 'Exception Handling',
          'subtopics': [
            'try-catch-finally',
            'throw & throws',
            'Custom Exceptions',
            'Checked vs Unchecked',
            'Exception Hierarchy',
          ],
        },
        {
          'name': 'File Handling',
          'subtopics': [
            'File Reader/Writer',
            'BufferedReader/Writer',
            'Serialization',
            'FileInputStream/OutputStream',
            'Java NIO Basics',
          ],
        },
        {
          'name': 'MySQL Basics',
          'subtopics': [
            'Database & Tables',
            'CRUD Operations',
            'Joins (Inner, Left, Right)',
            'Group By & Having',
            'Subqueries',
            'Indexing Basics',
            'Normalization',
            'JDBC Connection',
          ],
        },
        {
          'name': 'Postman',
          'subtopics': [
            'GET, POST, PUT, DELETE',
            'Request Headers',
            'Query Parameters',
            'Request Body (JSON)',
            'Environment Variables',
            'Collections & Tests',
          ],
        },
      ],
    },
    {
      'phase': 2,
      'title': 'SPRING BOOT MASTERY',
      'color': 0xFF4D9EFF,
      'icon': '🚀',
      'topics': [
        {
          'name': 'Spring Boot Core',
          'subtopics': [
            'Spring Boot Setup',
            'Project Structure',
            'application.properties',
            'Dependency Injection',
            '@Component, @Service, @Repository',
            'Bean Lifecycle',
            'Spring Boot DevTools',
            'Profiles (dev, prod)',
          ],
        },
        {
          'name': 'REST APIs',
          'subtopics': [
            'REST Principles',
            '@RestController',
            '@GetMapping, @PostMapping',
            '@PutMapping, @DeleteMapping',
            '@PathVariable & @RequestParam',
            '@RequestBody',
            'ResponseEntity',
            'HTTP Status Codes',
            'API Versioning',
          ],
        },
        {
          'name': 'DTO & Validation',
          'subtopics': [
            'DTO Pattern',
            'ModelMapper / MapStruct',
            '@Valid & @Validated',
            '@NotNull, @NotBlank, @Size',
            '@Email, @Min, @Max',
            'Custom Validators',
            'Global Exception Handler',
            '@ControllerAdvice',
          ],
        },
        {
          'name': 'JWT & Spring Security',
          'subtopics': [
            'Authentication vs Authorization',
            'Spring Security Config',
            'UserDetailsService',
            'JWT Token Generation',
            'JWT Token Validation',
            'JWT Filter Chain',
            'Role-Based Access Control',
            'Password Encoding (BCrypt)',
            'SecurityContext',
            'CORS Configuration',
          ],
        },
        {
          'name': 'Pagination & Sorting',
          'subtopics': [
            'Pageable & PageRequest',
            'Page & Slice',
            'Sort & Direction',
            'Custom Pagination Response',
          ],
        },
        {
          'name': 'File Upload',
          'subtopics': [
            'MultipartFile',
            'File Storage Service',
            'Image Upload API',
            'File Size Validation',
            'Serving Static Files',
          ],
        },
        {
          'name': 'Email Service',
          'subtopics': [
            'JavaMailSender Setup',
            'Simple Email',
            'HTML Email',
            'Email with Attachments',
            'Async Email Sending',
          ],
        },
        {
          'name': 'Logging',
          'subtopics': [
            'SLF4J & Logback',
            'Log Levels',
            'File-based Logging',
            'Log Patterns',
            'MDC (Mapped Diagnostic Context)',
          ],
        },
      ],
    },
    {
      'phase': 3,
      'title': 'MICROSERVICES ARCHITECTURE',
      'color': 0xFF8B5CF6,
      'icon': '🔗',
      'topics': [
        {
          'name': 'Microservices Fundamentals',
          'subtopics': [
            'Monolith vs Microservices',
            'Service Decomposition',
            'Inter-Service Communication',
            'Service Registry Pattern',
            'API Gateway Pattern',
            'Circuit Breaker Pattern',
            'Config Server',
          ],
        },
        {
          'name': 'API Gateway',
          'subtopics': [
            'Spring Cloud Gateway',
            'Route Configuration',
            'Filters & Predicates',
            'Rate Limiting',
            'Load Balancing',
          ],
        },
        {
          'name': 'Eureka Service Discovery',
          'subtopics': [
            'Eureka Server Setup',
            'Service Registration',
            'Service Discovery',
            'Health Checks',
            'Eureka Dashboard',
          ],
        },
        {
          'name': 'OpenFeign',
          'subtopics': [
            'Feign Client Setup',
            'Declarative REST Client',
            'Error Handling',
            'Feign Interceptors',
            'Retry Configuration',
          ],
        },
      ],
    },
  ];

  static final List<Map<String, dynamic>> dsaTopics = [
    {
      'name': 'Arrays',
      'icon': '📊',
      'color': 0xFF00FF88,
      'problems': [
        'Two Sum',
        'Best Time to Buy and Sell Stock',
        'Maximum Subarray',
        'Contains Duplicate',
        'Product of Array Except Self',
        'Merge Intervals',
        'Rotate Array',
        'Move Zeroes',
        'Spiral Matrix',
        'Set Matrix Zeroes',
      ],
    },
    {
      'name': 'Strings',
      'icon': '📝',
      'color': 0xFF4D9EFF,
      'problems': [
        'Reverse String',
        'Valid Anagram',
        'Longest Substring Without Repeating',
        'Palindrome Check',
        'String Compression',
        'Group Anagrams',
        'Longest Palindromic Substring',
        'String to Integer (atoi)',
      ],
    },
    {
      'name': 'Hashing',
      'icon': '🔑',
      'color': 0xFF8B5CF6,
      'problems': [
        'Two Sum (HashMap)',
        'Valid Sudoku',
        'Longest Consecutive Sequence',
        'Top K Frequent Elements',
        'Subarray Sum Equals K',
        'Intersection of Two Arrays',
      ],
    },
    {
      'name': 'Sorting',
      'icon': '🔀',
      'color': 0xFFFF6B9D,
      'problems': [
        'Bubble Sort',
        'Selection Sort',
        'Insertion Sort',
        'Merge Sort',
        'Quick Sort',
        'Counting Sort',
        'Sort Colors',
        'Kth Largest Element',
      ],
    },
    {
      'name': 'Recursion',
      'icon': '🔄',
      'color': 0xFFFFB340,
      'problems': [
        'Fibonacci',
        'Factorial',
        'Power of Two',
        'Subsets',
        'Permutations',
        'N-Queens',
        'Tower of Hanoi',
        'Rat in a Maze',
      ],
    },
    {
      'name': 'Linked List',
      'icon': '🔗',
      'color': 0xFF22D3EE,
      'problems': [
        'Reverse Linked List',
        'Detect Cycle',
        'Merge Two Sorted Lists',
        'Remove Nth Node From End',
        'Middle of Linked List',
        'Palindrome Linked List',
        'Intersection of Two Lists',
        'Flatten a Multilevel List',
      ],
    },
    {
      'name': 'Stack',
      'icon': '📚',
      'color': 0xFF00FF88,
      'problems': [
        'Valid Parentheses',
        'Min Stack',
        'Next Greater Element',
        'Evaluate Reverse Polish',
        'Daily Temperatures',
        'Largest Rectangle in Histogram',
      ],
    },
    {
      'name': 'Queue',
      'icon': '🚶',
      'color': 0xFF4D9EFF,
      'problems': [
        'Implement Queue using Stacks',
        'Sliding Window Maximum',
        'Design Circular Queue',
        'Task Scheduler',
        'Rotting Oranges',
      ],
    },
    {
      'name': 'Binary Search',
      'icon': '🔍',
      'color': 0xFF8B5CF6,
      'problems': [
        'Binary Search',
        'Search Insert Position',
        'Find First and Last Position',
        'Search in Rotated Sorted Array',
        'Find Peak Element',
        'Median of Two Sorted Arrays',
        'Koko Eating Bananas',
      ],
    },
    {
      'name': 'Trees',
      'icon': '🌳',
      'color': 0xFFFF6B9D,
      'problems': [
        'Inorder Traversal',
        'Maximum Depth',
        'Symmetric Tree',
        'Level Order Traversal',
        'Validate BST',
        'Lowest Common Ancestor',
        'Diameter of Binary Tree',
        'Path Sum',
        'Serialize and Deserialize',
      ],
    },
    {
      'name': 'Graphs',
      'icon': '🕸️',
      'color': 0xFFFFB340,
      'problems': [
        'BFS Traversal',
        'DFS Traversal',
        'Number of Islands',
        'Clone Graph',
        'Course Schedule',
        'Dijkstra\'s Algorithm',
        'Topological Sort',
        'Connected Components',
      ],
    },
    {
      'name': 'Dynamic Programming',
      'icon': '🧮',
      'color': 0xFF22D3EE,
      'problems': [
        'Climbing Stairs',
        'Coin Change',
        'Longest Common Subsequence',
        '0/1 Knapsack',
        'House Robber',
        'Longest Increasing Subsequence',
        'Edit Distance',
        'Unique Paths',
        'Word Break',
        'Partition Equal Subset Sum',
      ],
    },
  ];
}
